Clean board CSS with temporary deck array
WildCodeSchool/tlse0320-p2-SHBS pull request #25
Opened 2020-04-27 14:53 UTC by PaulCrtr

2020-05-05 14:59 UTC, Antropom submitted a review, later dismissed
OK

2020-05-06 08:40 UTC, Froyj requested changes

2020-05-06 08:40 UTC, Froyj commented on src/components/board/Board.jsx
> +const deckEnDur = [
Allez on s'applique sur les noms de variables :p (tout en anglais)

2020-05-06 08:40 UTC, Froyj commented on src/components/board/Board.jsx
> +                handleClick={() => {}}
attention code mort on enlève tant que c'est pas implementé

2020-05-06 08:40 UTC, Froyj commented on src/components/board/Board.jsx
> +                handleClick={() => {}}
idem code mort

2020-05-06 09:44 UTC, Antropom approved these changes
Requests done

2020-05-06 09:44 UTC, Antropom commented on src/components/board/Board.jsx
> +const deckEnDur = [
Corrections faites

2020-05-06 09:44 UTC, Antropom commented on src/components/board/Board.jsx
> +                handleClick={() => {}}
Done

2020-05-06 09:45 UTC, Antropom commented on src/components/board/Board.jsx
> +                handleClick={() => {}}
Done

2020-05-07 10:06 UTC, Froyj approved these changes

2020-05-07 13:55 UTC, merged