Sprint3/Opponent deck random creation & decks import to board
WildCodeSchool/tlse0320-p2-SHBS pull request #26
Opened 2020-04-28 13:27 UTC by jeromeHamilka

2020-05-05 15:10 UTC, Antropom approved these changes
OK

2020-05-07 10:26 UTC, Froyj requested changes

2020-05-07 10:26 UTC, Froyj commented on src/App.jsx
> +  };
pas utile il y a déjà setDeckOp qui fait ça. Cela rajoute une couche pour rien!

2020-05-11 06:39 UTC, Froyj approved these changes

2020-05-11 07:21 UTC, merged