Sprint3/real validation fight button
WildCodeSchool/tlse0320-p2-SHBS pull request #27
Opened 2020-04-28 21:39 UTC by jeromeHamilka

2020-05-05 15:20 UTC, Antropom submitted a review, later dismissed
OK

2020-05-07 11:13 UTC, Froyj requested changes

2020-05-07 11:13 UTC, Froyj commented on src/components/collection/Collection.jsx
> +      : this.setState({ validButtonFight: true });
attention un ternaire n'a pas vocation à exécuter des instructions mais plutôt à retourner des valeur. Le ternaire n'est pas un équivalent total du if else. Ici, il vaut mieux préférer un if else

2020-05-12 07:40 UTC, PaulCrtr commented on src/components/collection/Collection.jsx
> +      : this.setState({ validButtonFight: true });
Modifié

2020-05-12 07:45 UTC, Nicolas-Ramon approved these changes
ok

2020-05-12 07:45 UTC, PaulCrtr commented
Ok

2020-05-12 07:46 UTC, PaulCrtr approved these changes
Ok

2020-05-12 09:13 UTC, Froyj approved these changes

2020-05-12 09:25 UTC, merged