game algorithm : player and IA can attack
WildCodeSchool/tlse0320-p2-SHBS pull request #28
Opened 2020-05-05 14:23 UTC by PaulCrtr

2020-05-05 15:21 UTC, Antropom submitted a review, later dismissed
Vu en live

2020-05-07 11:54 UTC, Froyj requested changes

2020-05-07 11:54 UTC, Froyj commented on src/App.jsx
> +  };
pas la peine de wrapper dans une nouvelle fonction à chaque fois

2020-05-07 11:54 UTC, Froyj commented on src/components/collection/Collection.jsx
> +    this.props.addDeckOp(deckOpponent);
penser à destructurer (props et state) au début de la méthode

2020-05-12 07:46 UTC, jeromeHamilka submitted a review, later dismissed
ok

2020-05-12 07:57 UTC, Nicolas-Ramon approved these changes
ok, vu les changements en groupe

2020-05-12 07:57 UTC, jeromeHamilka approved these changes

2020-05-12 09:15 UTC, Froyj approved these changes

2020-05-12 09:25 UTC, merged